version: '3.6'

services:
  Plex:
    container_name: Plex

    image: plexinc/pms-docker:public

    labels:
      - traefik.enable=false

    volumes:
      - PlexData:/data
      - PlexDB:/config
      - /mnt/ramdisk:/transcode

    env_file:
      - Plex.env

    network_mode: "host"

    domainname: gensosekai.com
    hostname: Plex
    restart: unless-stopped



volumes:
  PlexDB:
    external: true
  PlexData:
    external: true
