version: '3.3'

services:
  Sonarr:
    container_name: Sonarr
    image: linuxserver/sonarr
    volumes:
      - /mnt/raid5/DockerVolumes/TransmissionDownloads:/downloads
      - /mnt/raid5/DockerVolumes/PlexData:/tv
      - SonarrConfig:/config
    environment:
      PUID: 1002
      PGID: 1004
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'WebGateway'
      traefik.http.routers.sonarr-secure.entrypoints: 'websecure'
      traefik.http.routers.sonarr-secure.rule: 'Host(`sonarr.gensosekai.com`)'
      traefik.http.routers.sonarr-secure.middlewares: 'middlewares-oauth@file'
      traefik.http.routers.sonarr-secure.service: 'sonarr'
      traefik.http.routers.sonarr-secure.tls: 'true'
      traefik.http.routers.sonarr-secure.tls.certresolver: 'lets-encrypt'
      traefik.http.services.sonarr.loadbalancer.server.port: '8989'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.20
    restart: unless-stopped

  Lidarr:
    container_name: Lidarr
    image: linuxserver/lidarr
    volumes:
      - /mnt/raid5/DockerVolumes/TransmissionDownloads:/downloads
      - /mnt/raid5/DockerVolumes/PlexData:/music
      - LidarrConfig:/config
    environment:
      PUID: 1002
      PGID: 1004
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'WebGateway'
      traefik.http.routers.lidarr-secure.entrypoints: 'websecure'
      traefik.http.routers.lidarr-secure.rule: 'Host(`lidarr.gensosekai.com`)'
      traefik.http.routers.lidarr-secure.middlewares: 'middlewares-oauth@file'
      traefik.http.routers.lidarr-secure.service: 'lidarr'
      traefik.http.routers.lidarr-secure.tls: 'true'
      traefik.http.routers.lidarr-secure.tls.certresolver: 'lets-encrypt'
      traefik.http.services.lidarr.loadbalancer.server.port: '8686'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.22
    restart: unless-stopped

  Radarr:
    container_name: Radarr
    image: linuxserver/radarr
    volumes:
      - /mnt/raid5/DockerVolumes/TransmissionDownloads:/downloads
      - /mnt/raid5/DockerVolumes/PlexData:/movies
      - RadarrConfig:/config
    environment:
      PUID: 1002
      PGID: 1004
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'WebGateway'
      traefik.http.routers.radarr-secure.entrypoints: 'websecure'
      traefik.http.routers.radarr-secure.rule: 'Host(`radarr.gensosekai.com`)'
      traefik.http.routers.radarr-secure.middlewares: 'middlewares-oauth@file'
      traefik.http.routers.radarr-secure.service: 'radarr'
      traefik.http.routers.radarr-secure.tls: 'true'
      traefik.http.routers.radarr-secure.tls.certresolver: 'lets-encrypt'
      traefik.http.services.radarr.loadbalancer.server.port: '7878'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.21
    restart: unless-stopped

  Transmission:
    container_name: Transmission
    image: linuxserver/transmission
    volumes:
      - TransmissionDownloads:/downloads
      - PlexData:/data
      - TransmissionCfg:/config
      - TransmissionWatch:/watch
    env_file:
      - Transmission.env
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'WebGateway'
      traefik.http.routers.transmission-web.rule: 'Host(`transmissionweb.gensosekai.com`)'
      traefik.http.routers.transmission-web.entrypoints: 'websecure'
      traefik.http.routers.transmission-web.service: 'transmission-web'
      traefik.http.routers.transmission-web.tls: 'true'
      traefik.http.routers.transmission-web.tls.certresolver: 'lets-encrypt'
      traefik.http.services.transmission-web.loadbalancer.server.port: '9091'
      traefik.tcp.routers.transmission-client.rule: 'HostSNI(`transmission.gensosekai.com`)'
      traefik.tcp.routers.transmission-client.entrypoints: 'websecure'
      traefik.tcp.routers.transmission-client.service: 'transmission-client'
      traefik.tcp.routers.transmission-client.tls: 'true'
      traefik.tcp.routers.transmission-client.tls.certresolver: 'lets-encrypt'
      traefik.tcp.services.transmission-client.loadbalancer.server.port: '9091'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.23
    restart: unless-stopped

  Tautulli:
    container_name: Tautulli
    image: linuxserver/tautulli:latest
    volumes:
      - TautulliConfig:/config
      - TautulliLogs:/logs
    environment:
      PUID: 1002
      PGID: 1004
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'WebGateway'
      traefik.http.routers.tautulli-secure.entrypoints: 'websecure'
      traefik.http.routers.tautulli-secure.rule: 'Host(`tautulli.gensosekai.com`)'
      traefik.http.routers.tautulli-secure.middlewares: 'middlewares-oauth@file'
      traefik.http.routers.tautulli-secure.service: 'tautulli'
      traefik.http.routers.tautulli-secure.tls: 'true'
      traefik.http.routers.tautulli-secure.tls.certresolver: 'lets-encrypt'
      traefik.http.services.tautulli.loadbalancer.server.port: '8181'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.242
    restart: unless-stopped

  Plex:
    container_name: Plex
    image: plexinc/pms-docker:public
    labels:
      traefik.enable: 'false'
    volumes:
      - PlexData:/data
      - PlexDB:/config
      - /mnt/ramdisk:/transcode
    env_file:
      - Plex.env
    network_mode: "host"
    restart: unless-stopped

volumes:
  TransmissionWatch:
    external: true
  TransmissionCfg:
    external: true
  TransmissionDownloads:
    external: true
  PlexDB:
    external: true
  PlexData:
    external: true
  TautulliConfig:
    external: true
  TautulliLogs:
    external: true
  RadarrConfig:
    external: true
  LidarrConfig:
    external: true
  SonarrConfig:
    external: true
  PlexData:
    external: true
  TransmissionDownloads:
    external: true

networks:
  WebGateway:
    external: true
