version: "3.1"
services:
  Mealie:
    container_name: Mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    volumes:
      - Mealie:/app/data
    env_file: 
      - Mealie.env
    labels:
      traefik.enable: 'true'
      traefik.docker.network: proxy
      traefik.http.routers.mealie-secure.entrypoints: websecure
      traefik.http.routers.mealie-secure.rule: Host(`mealie.gensosekai.com`)
      traefik.http.routers.mealie-secure.service: mealie
      traefik.http.routers.mealie-secure.tls: 'true'
      traefik.http.routers.mealie-secure.tls.certresolver: lets-encrypt
      traefik.http.services.mealie.loadbalancer.server.port: 80
    networks:
      WebGateway:
        ipv4_address: 10.10.10.15

  MealiePostgres:
    container_name: MealiePostgres
    image: postgres:14
    restart: unless-stopped
    env_file: 
      - MealiePostgres.env
    labels:
      traefik.enable: 'false'
    networks:
      WebGateway:
        ipv4_address: 10.10.10.16
    volumes:
      - MealiePostgres:/var/lib/postgresql/data

volumes:
  Mealie:
    external: true
  MealiePostgres:
    external: true

networks:
  WebGateway:
    external: true
